spring.application.name=TravelAgencyApp

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/travel_agency
spring.datasource.username=root
spring.datasource.password=123456

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://127.0.0.1:8180/realms/travel-agency

spring.security.oauth2.client.registration.keycloak.client-id=booking-internal-client
spring.security.oauth2.client.registration.keycloak.client-secret=ZtMSCORurWPZc5YQ6k1jEkyax9qVRjhY
spring.security.oauth2.client.registration.keycloak.authorization-grant-type=client_credentials

spring.security.oauth2.client.provider.keycloak.token-uri=http://127.0.0.1:8180/realms/travel-agency/protocol/openid-connect/token

logging.level.org.hibernate.SQL=debug
logging.level.org.hibernate.orm.jdbc.bind=trace
logging.level.com.myProject=info
logging.level.org.springframework.security=trace

server.port=6060

management.endpoints.web.exposure.include=*
